### ISSUE TITLE
Enabling log causes no colour

### ISSUE THREAD

**Issue by oldmankit** [xmrig/xmrig-nvidia#102]
With the following options specified in config.json, colours are working as normal:

`"colors": true,
"log-file": null,`

However, as soon as I specify a log file, like this:

`  "colors": true,
    "log-file": "xmrig.log",`

Then colors no longer work. Everything is just white text on black background.

I'd like to have both colors and a log file!

Using version 2.4.2 on Windows 10.

**Comment by metalurgus** [comment]
I've found a place in the code, which disables colors if log file is specified:
https://github.com/xmrig/xmrig-nvidia/blob/f22ddbbeebcafecbcab061c65a562d6bd9ae2cb8/src/Options.cpp#L457
I didn't find a reason why the colors need to be disabled if the log file specified, because they are not going to hurt file loging anyhow. 
I will try to make a fix and a pool request for that today after work.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/issues/103
