### ISSUE TITLE
Reduce CPU usage

### ISSUE THREAD

**Issue by calvintam236** [xmrig/xmrig-nvidia#14]
I notice that `xmrig-nvidia` uses 6% CPU on my AMD 1700 when running. Other miners, e.g. `ethminer`, `ebwf-miner`, don't go over 1%. Any optimization you can do to reduce the CPU usage (I am mining on CPU as well, so less CPU usage = higher hashrate)?

**Comment by calvintam236** [comment]
@xmrig any chance you can take a look why `xmrig-nvidia` is using CPU, and how to reduce it?

**Comment by xmrig** [comment]
1. What GPU?
2. Setting for that GPU.
3. Diff, it's important because each successful share recalculated on CPU.

6% looks pretty bad, because it means 1 core fully loaded (100% / 16). On my computer I don't see abnormal CPU usage. I will continue work on this miner soon, will try fugue it out.
Thank you.

**Comment by calvintam236** [comment]
1. 1700 Founder Ed.
2. auto
3. It might be the reason for the CPU usage. Maybe recalculation can be done by GPU?

**Comment by saphiretr** [comment]
GTX 1080 Ti and CPU usage is 10-12%.

**Comment by jimduchek** [comment]
The bfactor/bsleep settings seem to affect CPU usage quite a bit.
