### ISSUE TITLE
I know Scanners always report as virus, only 1 download reports this one

### ISSUE THREAD

**Issue by Jtek3d** [xmrig/xmrig-nvidia#277]
i know the scanners like avg always report the miners as viruses or more like malware. 
thing is this time Only the Cuda 8 win64 is reporting this possible trojan  cuda 9, cuda 10 shows the typical so it doesnt even warn me but with the cuda 8 different story.
avg is reporting one called 
"BV:Miner-AZ"  <----  which this is normal is just a miner thing.
"Win32:HarHarMiner-A" <---------  calling it a trojan 
both in the same cuda 8 download, both same .exe i do trust xmrig but just to be 100% safe i'm just gonna download the source and compile.. it might be nothing but the trojan flaged part just scares me a little. and i know i can exclude from the list and still use it. just thought i'd say something cause it seems to be reporting and extra one is all.

tried posting a screen shot but it won't let me. contact me if you'd like a screenshot or more info

**Comment by Spudz76** [comment]
Virus scanners use Heuristics - which is a fancy word for assumptive guess.

It sees some pattern in there that "looks a lot like" the HarHarMiner thing, but isn't.  False positive, false identification, it's being racist against any code that "looks like" those miner(s) it hates.  So eventually, all miners look the same (due to main code being the same math/algo/procedures).

Thus is the problem with profiling / heuristics / guessing / assumptions.  Very likely safe, where you would want to be careful is if it was a non-mining app that said it had miner code in it.  But since this is a miner app, and it's finding miner code in it... well of course it did.  Nobody is going to attach a miner trojan onto an on-purpose-miner, that would be silly.  They want to hack-mine on a box that isn't already being mined by the legitimate owner (low CPU use / dumb web-warrior / not power-user) and so they put trojans on everything except actual mining apps.
