### ISSUE TITLE
Help V.2.14.5 pool request update before November

### ISSUE THREAD

**Issue by mbahcrypto** [xmrig/xmrig-nvidia#303]
I am using xmrig nvidia version 2.14.5 but pool requests that it be updated to the latest version because there will be a new algo fork in November, please help!
![2019-10-31-085621_1366x768_scrot](https://user-images.githubusercontent.com/57203985/67913652-54697200-fbc0-11e9-9d4c-67a054b61e62.jpg)

thanks for the support

**Comment by Spudz76** [comment]
Build from the `dev` branch, or override your useragent so the pool doesn't know you're running the older release.  Or run via their `meta-miner` proxy which I think cloaks your useragent automatically (and adds coin switching).

Unsure when there will be a precompiled release with RX included.  Also RX won't work on your GPU anyway due to not enough memory so it's sort of not an issue anyway (you can't mine Monero on that GPU after the fork regardless, you will have to mine the other algos MoneroOcean offers and use their auto-exchange to XMR payout).  My miners on there are rarely mining actual CN-R (current Monero) anyway, they tend to chew on the Heavy, Lite, or Pico variants most of the time, and my CPUs tend to chew the current RandomX algos.  And none of my GPUs have enough to run RandomX (1GB up to 2GB) so it doesn't matter.

**Comment by Spudz76** [comment]
To override useragent string change the config option:
`    "user-agent": null,`
to something like:
`    "user-agent": "XMRig-NVIDIA 2.14.5-dev",`
which would cloak your release binary as the dev version and stop the complaint

**Comment by mbahcrypto** [comment]
thank you for your help ... I do have a plan to upgrade some gpu but because there is a fork so I am still waiting,for info of the best gpu for mining RX.
