### ISSUE TITLE
[Suggestion] Please provide a linux binary

### ISSUE THREAD

**Issue by leovarmak** [xmrig/xmrig-nvidia#45]
Hey,
Please provide a linux binary so that noobs like me can use.

**Comment by adem4ik** [comment]
Hello! The problem is that Linux distributions have different versions of different libraries. And the developer can't provide binaries for every existing Linux distribution. If you're on Ubuntu 16.04+ there should be no problem for you to compile it by yourself as described here https://github.com/xmrig/xmrig-nvidia/wiki/Ubuntu-Build On the side note you can even disable developer fee by the manual compilation!

P.S. Anyway if you are Linux user you have to learn how to compile and how to get needed version of any application or library.
